import React from "react";
import "./IntroPopup.css";

const IntroPopup = ({ onClose }) => {
  return (
    <div className="intro-container">
      <div className="intro-background">
        <img className="intro-image" src="/assets/spacecraft.jpg" alt="Meteor"/> 
        <div className="intro-content">
          <h2>Welcome to the AR Game!</h2>
          <p>Instructions on how to play the game go here...
          Instructions on how to play the game go here...
          Instructions on how to play the game go here...
          Instructions on how to play the game go here...
          Instructions on how to play the game go here...
          Instructions on how to play the game go here...
          Instructions on how to play the game go here...
          Instructions on how to play the game go here...
          Instructions on how to play the game go here...
          Instructions on how to play the game go here...
          </p>
        </div>
        <button className="intro-button" onClick={onClose}>CLOSE</button>
      </div>
    </div>
  );
};

export default IntroPopup;
